jobby/account/views.py
from flask import render_template, request, Blueprint, redirect, url_for, flash, abort
from werkzeug.security import generate_password_hash, check_password_hash
from jobby.models import Users, Notification
from datetime import datetime
from jobby import db, login_manager
from flask_login import login_user, logout_user, login_required, current_user
from utils import send_confirmation_email

account = Blueprint('account',__name__)

@login_manager.user_loader
def load_user(id):
    return Users.query.get(int(id))

@account.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('public.index'))
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = Users.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('manage.dashboard'))
            else:
                flash('Wrong Credentials! Check your spelling.')
                return render_template('account/login.html')
        else:
            flash('Wrong Credentials! Check your spelling.')
            return render_template('account/login.html')
    return render_template('account/login.html')

@account.route('/confirm_email/<token>')
def confirm_email(token):
    user = Users.verify_confirmation_token(token)
    if not user:
        abort(404)
    notif = Notification.query.filter_by(notification_to=current_user, not_type=2).first_or_404()
    db.session.delete(notif)
    user.email_approved = True
    db.session.commit()
    flash('Your email address has been confirmed!')
    return render_template('dashboard/dashboard.html')

@account.route('/signup', methods=['GET','POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('public.index'))
    if request.method == 'POST':
        name = request.form['name'].capitalize()
        surname = request.form['surname'].capitalize()
        email = request.form['email']
        password = request.form['password']
        hashed_password = generate_password_hash(password, method='sha256')
        existing_user = Users.query.filter_by(email=email).first()
        if existing_user is None:
            if email.startswith('demo'):
                user = Users(name=name, surname=surname, email=email,
                    password=hashed_password, member_since=datetime.utcnow(),
                    status='employer', email_approved=True)
                db.session.add(user)
                db.session.commit()
            else:
                user = Users(name=name, surname=surname, email=email,
                    password=hashed_password, member_since=datetime.utcnow(),
                    status='employer')
                notif = Notification(notification_to=user, not_type=2)
                db.session.add(user)
                db.session.add(notif)
                db.session.commit()
                #uncomment below code if you want to send confirmation email
                #send_confirmation_email(user)
            login_user(user)
            return render_template('account/welcome.html')
        flash('This email already being used!')
        return render_template('account/signup.html')

    return render_template('account/signup.html')

@account.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('public.index'))

jobby/message/views.py
from flask import render_template, Blueprint, request, jsonify, flash, redirect, url_for, abort
from flask_login import current_user, login_required
from jobby.models import Users, Messages, Bids, Offers
from jobby import db, last_updated
from sqlalchemy import or_, and_
from datetime import datetime
from flask_socketio import emit
from .. import socketio

message = Blueprint('message',__name__)

@message.route('/get-message/<type_id>')
@login_required
def getMessage(type_id):
    itemType, itemId = type_id.split('_')
    if itemType == 'b':
        data = Bids.query.filter_by(id=itemId).first_or_404()
        if current_user == data.bidder or current_user == data.bidded.poster:
            return jsonify({"message": data.message})
    elif itemType == 'o':
        data = Offers.query.filter_by(id=itemId, offered=current_user).first_or_404()
        return jsonify({"message": data.message})
    else:
        jsonify({"message": 'Some thing went wrong'})

@message.route('/get-recipient/<int:recipient_id>')
@login_required
def getRecipient(recipient_id):
    user = Users.query.filter_by(id=recipient_id).first_or_404()
    return jsonify({"username": user.name})

@socketio.on('send message')
def handle_message(data):
    recipient_id = data['to']
    body = data['body']
    recipient = Users.query.filter_by(id=recipient_id).first()
    msg = Messages(body=body, recipient=recipient, sender=current_user)
    db.session.add(msg)
    db.session.commit()
    emit("message success", {'success': True})

@socketio.on('connect')
def handle_connection():
    current_user.message_sid = request.sid
    db.session.commit()

# @socketio.on('start writing')
# def handle_writing(data):
#     print("writing event fired")
#     recipient_id = data['recipient_id']
#     recipient = Users.query.filter_by(id=recipient_id).first()
#     print("recipient_id ", recipient_id)
#     emit("put writing field", {'sender_id': current_user.id, 'recipient_id': recipient_id}, room=recipient.message_sid)

@socketio.on('private message')
def handle_private_message(data):
    recipient_id = data['recipient']
    recipient = Users.query.filter_by(id=recipient_id).first()
    private_msg = data['msg']
    new_message = Messages(body=private_msg, recipient=recipient, sender=current_user)
    db.session.add(new_message)
    db.session.commit()
    emit('message sent back', {"prv": private_msg, "sender_id": current_user.id}, room=recipient.message_sid)

@message.route('/get-all-message/<int:person_id>')
@login_required
def handle_all_messages(person_id):
    recipient = Users.query.get(person_id)
    msgs = db.session.query(Messages.body, Messages.timestamp, Messages.sender_id, Messages.recipient_id).filter(or_(and_(Messages.sender_id==current_user.id,
        Messages.recipient_id==person_id),
        and_(Messages.sender_id==person_id, Messages.recipient_id==current_user.id))).all()

    return jsonify({'payload': msgs, 'currentUserId': current_user.id, "recipient_name": recipient.name+" "+recipient.surname, "imgSrcSender": current_user.profile_picture, "imgSrcReciever": recipient.profile_picture})

def get_users(f):
    users = []
    for i in f:
        user = Users.query.get(i)
        users.append(user)
    return users

@message.route('/messages')
@login_required
def messages():
    current_user.last_message_read_time = datetime.utcnow()
    db.session.commit()
    as_a_recipient = db.session.query(Messages.sender_id).filter(Messages.recipient_id==current_user.id).distinct().all()
    as_a_sender = db.session.query(Messages.recipient_id).filter(Messages.sender_id==current_user.id).distinct().all()

    return render_template('message/messages.html',c=get_users(set(as_a_recipient+as_a_sender)), last_updated=last_updated)

jobby/posttask/views.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from flask_login import login_required, current_user
from jobby import db, last_updated
from jobby.models import Users, Tasks, TaskSkills
import bleach, uuid, os
from PIL import Image
from werkzeug.utils import secure_filename
from datetime import datetime
from utils import allowed_img_file, get_extension, UPLOAD_TASK_FOLDER, crop_max_square

posttask = Blueprint('posttask',__name__)

@posttask.route('/posttask', methods=['GET', 'POST'])
@login_required
def post_task():
    if request.method == 'POST':
        project_name = request.form["project_name"].capitalize()
        location = request.form["location"]
        budget_min = request.form["budget_min"] or 0
        budget_max = request.form["budget_max"] or 0
        category = request.form["category"]
        skills_list = request.form.getlist('skills_list')[0].split(',')

        if len(skills_list) > 5 or len(skills_list) < 1:
            return jsonify({'success': False, 'msg': 'Add at least 1 at most 5 skills!'})

        description = bleach.clean(request.form["description"], tags=bleach.sanitizer.ALLOWED_TAGS+['u', 'br', 'p'])

        task = Tasks(project_name=project_name, location=location, budget_min=budget_min, time_posted=datetime.now(),
                     budget_max=budget_max, category=category, description=description, user_id=current_user.id)

        if 'file' in request.files:
            file = request.files['file']
            filename = file.filename
            if allowed_img_file(filename):
                filename = secure_filename(filename)
                unique_filename = str(uuid.uuid4())+get_extension(filename)
                task.task_pic = unique_filename
                image = Image.open(file)
                i = crop_max_square(image).resize((356, 200), Image.LANCZOS)
                i.save(os.path.join(UPLOAD_TASK_FOLDER, unique_filename), quality=95)
            else:
                return jsonify({'success': False, 'msg': 'Allowed image files jpeg, png, jpg'})
        else:
            return jsonify({'success': False, 'msg': 'Please add an image relevant to your project!'})

        db.session.add(task)
        db.session.commit()

        for skill in skills_list:
            tskills = TaskSkills(skill=skill.capitalize(), task_id=task.id)
            db.session.add(tskills)
        db.session.commit()
        return jsonify({'success': True, 'msg': url_for('public.task_page', task_url=task.generate_task_link())})
    else:
        if not current_user.email_approved:
            flash('Your email has not been confirmed yet. You cannot post a project!')
        return render_template('tasks/post-a-task.html', last_updated=last_updated)

jobby/setting/views.py
from flask import render_template, Blueprint, request, url_for, jsonify
from flask_login import current_user, login_required
from jobby import db, last_updated
from werkzeug.security import check_password_hash, generate_password_hash

setting = Blueprint('setting',__name__)

@setting.route('/setting/security', methods=['POST'])
@login_required
def setting_security():
    data = request.get_json(force=True)
    password = data['password']
    new_password = data['new_password']
    confirm_password = data['confirm_password']
    if len(new_password.strip()) < 6 or new_password != confirm_password or not check_password_hash(current_user.password, password):
        return jsonify({"success": False, "msg": "Some thing went wrong. Reason might be your password length is less than 6, or passwords didn't match or your password is not on our systems!"})
    else:
        current_user.password = generate_password_hash(new_password, method='sha256')
        db.session.commit()
        return jsonify({"success": True, "msg": "Your password has been changed!"})


@setting.route('/setting')
@login_required
def setting_page():
    return render_template('setting/settings.html', last_updated=last_updated)

jobby/templates/header-public.html
<!-- Navbar STart -->
<header id="topnav" class="defaultscroll sticky">
    <div class="container">
        <!-- Logo container-->
        <a class="logo" href="{{ url_for('public.index') }}">
            <img src="{{ url_for('static', filename='images/jobby.png')}}" height="36" class="logo-light-mode" alt="">
        </a>
        <div class="buy-button">
          {% if current_user.is_authenticated %}
          <li class="list-inline-item mb-0" style="margin-right: 10px;">
            <a href="{{ url_for('posttask.post_task') }}">
              <div class="btn btn-outline-primary">Post Project</div>
            </a>
          </li>

            <li class="list-inline-item mb-0">
              <div class="dropdown dropdown-primary">
                  <button type="button" class="btn btn-icon btn-soft-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="uil uil-user align-middle icons"></i></button>
                  <div class="dropdown-menu dd-menu dropdown-menu-end bg-white shadow rounded border-0 mt-3 py-3" style="width: 200px;">
                      <a class="dropdown-item text-dark" href="{{ url_for('editProfile.editProfile_page') }}"><i class="uil uil-user align-middle me-1"></i> Edit Profile</a>
                      {% if current_user.status == 'freelancer' %}
                        <a class="dropdown-item text-dark" href="{{ url_for('manage.activeBids') }}"><i class="uil uil-clipboard-notes align-middle me-1"></i> Active Bids</a>
                      {% else %}
                        <a class="dropdown-item text-dark" href="{{ url_for('manage.manageTasks') }}"><i class="uil uil-clipboard-notes align-middle me-1"></i> Projects</a>
                      {% endif %}
                      <div class="dropdown-divider my-3 border-top"></div>
                      <a class="dropdown-item text-dark" href="{{ url_for('account.logout') }}"><i class="uil uil-sign-out-alt align-middle me-1"></i> Logout</a>
                  </div>
              </div>
            </li>
          {% else %}
            <a href="{{ url_for('account.signup') }}" class="btn btn-primary">Sign Up</a>
          {% endif %}
        </div><!--end login button-->
        <!-- End Logo container-->
        <div class="menu-extras">
            <div class="menu-item">
                <!-- Mobile menu toggle-->
                <a class="navbar-toggle" id="isToggle" onclick="toggleMenu()">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </div>
        </div>

        <div id="navigation">
            <!-- Navigation Menu-->
            <ul class="navigation-menu">
                <li><a href="{{ url_for('public.browseTasks') }}" class="sub-menu-item">Projects</a></li>
                <li><a href="{{ url_for('public.browseFreelancers') }}" class="sub-menu-item">Freelancers</a></li>
                {% if current_user.is_authenticated %}
                  <li><a href="{{ url_for('manage.dashboard') }}" class="sub-menu-item">Dashboard</a></li>
                {% endif %}
            </ul><!--end navigation menu-->
        </div><!--end navigation-->
    </div><!--end container-->
</header><!--end header-->
<!-- Navbar End -->

jobby/templates/header.html
<header id="header-container" class="fullwidth dashboard-header not-sticky">

	<!-- Header -->
	<div id="header">
		<div class="container">

			<!-- Left Side Content -->
			<div class="left-side">

				<!-- Logo -->
				<div id="logo">
					<a href="{{ url_for('public.index') }}"><img src="{{ url_for('static', filename='images/jobby.png')}}" alt=""></a>
				</div>

				<!-- Main Navigation -->
				<nav id="navigation">
					<ul id="responsive">
						<li><a href="{{ url_for('public.browseTasks') }}"><b>PROJECTS</b></a></li>

						<li><a href="{{ url_for('public.browseFreelancers') }}"><b>FREELANCERS</b></a></li>

						{% if current_user.is_authenticated %}
							<li><a href="{{ url_for('manage.dashboard') }}"><b>DASHBOARD</b></a></li>
							<li class="onlyMobile"><a href="{{ url_for('manage.reviews') }}"><b>REVIEWS</b></a></li>
							<li class="onlyMobile"><a href="{{ url_for('account.logout') }}"><b>LOGOUT</b></a></li>
						{% endif %}
						{% if current_user.is_anonymous %}
							<li class="onlyMobile"><a href="{{ url_for('account.login') }}"><b>LOGIN</b></a></li>
							<li class="onlyMobile"><a href="{{ url_for('account.signup') }}"><b>SIGN UP</b></a></li>
						{% endif %}
					</ul>
				</nav>
				<div class="clearfix"></div>
				<!-- Main Navigation / End -->

			</div>
			<!-- Left Side Content / End -->

			{% if current_user.is_authenticated %}
			<!-- Right Side Content / End -->
			<div class="right-side">
				<div class="header-widget" id="hideitmobile">
        	<a href="{{ url_for('posttask.post_task') }}" class="btn btn-post margin-top-20" style="color: white;">Post Project</a>
        </div>

				<!--  User Notifications -->
				<div class="header-widget hide-on-mobile">

					<!-- Notifications -->
					<div class="header-notifications">

						<!-- Trigger -->
						<div class="header-notifications-trigger">
								<a href="#"><i class="icon-feather-bell"><span name="badge">{{ current_user.num_not() }}</span></i></a>
						</div>

						<!-- Dropdown -->
						<div class="header-notifications-dropdown">

							<div class="header-notifications-headline">
								<h4>Notifications</h4>
								<button class="mark-as-read ripple-effect-dark" title="Mark as read" data-tippy-placement="left">
									<i class="icon-feather-check-square"></i>
								</button>
							</div>

							<div class="header-notifications-content">
								<div class="header-notifications-scroll" data-simplebar>
									<ul>
										{% for nt in current_user.new_notifications() %}
											{% if nt.not_type == 1 %}
												<li>
													<a href="{{ url_for('manage.manageBidders', task_id=nt.notedTask.id) }}">
														<span class="notification-icon"><i class="icon-material-outline-gavel"></i></span>
														<span class="notification-text">
															<strong>{{ nt.notification_from }} </strong> bidded for <span class="color">{{ nt.notedTask }}.</span>
														</span>
													</a>
												</li>
											{% endif %}
											{% if nt.not_type == 2 %}
												<li>
													<a href="#">
														<span class="notification-icon"><i class="icon-line-awesome-info"></i></span>
														<span class="notification-text">
															<strong>Please confirm your email!</strong>
														</span>
													</a>
												</li>
											{% endif %}
											{% if nt.not_type == 3 %}
												<li>
													<a href="{{ url_for('manage.activeBids') }}">
														<span class="notification-icon" style="background: green; color: white;"><i class="icon-material-outline-check-circle"></i></span>
														<span class="notification-text">
															<strong>congratulations!</strong> You won <span class="color">{{ nt.notedTask }}</span>
														</span>
													</a>
												</li>
											{% endif %}
											{% if nt.not_type == 4 %}
											<li>
												<a href="{{ url_for('manage.manageOffers') }}">
													<span class="notification-icon"><i class="icon-material-outline-local-offer"></i></span>
													<span class="notification-text">
														<strong>{{ nt.notification_from }} </strong> has proposed you an offer.
													</span>
												</a>
											</li>
											{% endif %}
											{% if nt.not_type == 5 %}
											<li>
												<a href="{{ url_for('manage.reviews') }}">
													<span class="notification-icon"><i class="icon-material-outline-rate-review"></i></span>
													<span class="notification-text">
														<strong>{{ nt.notification_from }} </strong> has reviewed your <span class="color">{{ nt.notedTask }}</span> work.
													</span>
												</a>
											</li>
											{% endif %}
										{% endfor %}
										{% if current_user.num_not() == 0 %}
											<li>
												<a href="#">
													<span class="notification-icon"><i class="icon-line-awesome-info"></i></span>
													<span class="notification-text">
														<strong>You don't have any notification</strong>
													</span>
												</a>
											</li>
										{% endif %}
									</ul>
								</div>
							</div>

						</div>

					</div>

					<!-- Messages -->
					<div class="header-notifications">
						<div class="header-notifications-trigger">
							<a href="#"><i class="icon-feather-mail"></i><span name="badge">{{ current_user.num_new_messages() }}</span></a>
						</div>

						<!-- Dropdown -->
						<div class="header-notifications-dropdown">

							<div class="header-notifications-headline">
								<h4>Messages</h4>
								<button class="mark-as-read ripple-effect-dark" title="Mark all as read" data-tippy-placement="left">
									<i class="icon-feather-check-square"></i>
								</button>
							</div>

							<div class="header-notifications-content">
								<div class="header-notifications-scroll" data-simplebar>
									<ul>
										{% for msg in current_user.new_messages() %}
										<li class="notifications-not-read">
											<a href="{{ url_for('message.messages') }}">
												<span class="notification-avatar status-online"><img src="{{ url_for('static', filename='images/'+msg.sender.profile_picture) }}" alt=""></span>
												<div class="notification-text">
													<strong>{{ msg.sender }}</strong>
													<p class="notification-msg-text">{{ msg.body }}</p>
													<span class="color">{{ msg.timestamp.strftime('%d:%m:%Y saat %H:%M') }}</span>
												</div>
											</a>
										</li>
										{% endfor %}
									</ul>
								</div>
							</div>

							<a href="{{ url_for('message.messages') }}" class="header-notifications-button ripple-effect button-sliding-icon">See all messages<i class="icon-material-outline-arrow-right-alt"></i></a>
						</div>
					</div>

				</div>
				<!--  User Notifications / End -->

				<!-- User Menu -->
				<div class="header-widget">

					<!-- Messages -->
					<div class="header-notifications user-menu">
						<div class="header-notifications-trigger">
							<a href="#"><div class="user-avatar status-online"><img src="{{ url_for('static', filename='images/'+current_user.profile_picture) }}" alt=""></div></a>
						</div>

						<!-- Dropdown -->
						<div class="header-notifications-dropdown">

							<!-- User Status -->
							<div class="user-status">

								<!-- User Name / Avatar -->
								<div class="user-details">
									<div class="user-avatar status-online"><img src="{{ url_for('static', filename='images/'+current_user.profile_picture) }}" alt=""></div>
									<div class="user-name">
										{% if current_user.name %}
											{{ current_user.get_full_name() }}
										{% else %}
											{{ current_user.email }}
										{% endif %}

										{% if current_user.status == 'employer' %}
											<span>Employer</span>
										{% else %}
											<span>Freelancer</span>
										{% endif %}
									</div>
								</div>

								<!-- User Status Switcher -->
								<div class="status-switch" id="snackbar-user-status">
									<label class="user-online current-status">Online</label>
									<label class="user-invisible">Offline</label>
									<!-- Status Indicator -->
									<span class="status-indicator" aria-hidden="true"></span>
								</div>
						</div>

						<ul class="user-menu-small-nav">
							{% if current_user.status == 'freelancer' %}
								<li><a href="{{ url_for('public.freelancer', user_id=current_user.id) }}"><i class="icon-material-outline-account-circle"></i> My Profile</a></li>
							{% else %}
								<li><a href="{{ url_for('editProfile.editProfile_page') }}"><i class="icon-material-outline-account-circle"></i> Edit Profile</a></li>
							{% endif %}
							<li><a href="{{ url_for('setting.setting_page') }}"><i class="icon-material-outline-settings"></i> Settings</a></li>
							<li><a href="{{ url_for('account.logout') }}"><i class="icon-material-outline-power-settings-new"></i> Logout </a></li>
						</ul>

						</div>
					</div>

				</div>
				<!-- User Menu / End -->
				{% else %}
			 <!-- Right Side Content / End -->
				<div class="right-side">
					<div class="header-widget">
						<a href="{{ url_for('account.login') }}" class="log-in-button"><i class="icon-feather-log-in"></i> <span>Log In / Sign Up</span></a>
					</div>
				{% endif %}
				<!-- Mobile Navigation Button -->
				<span class="mmenu-trigger">
					<button class="hamburger hamburger--collapse" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
				</span>

			</div>
			<!-- Right Side Content / End -->

		</div>
	</div>
	<!-- Header / End -->
</header>

<script src="{{ url_for('static', filename='js/header.js')}}"></script>

jobby/templates/sidebar.html
<div class="dashboard-sidebar">
  <div class="dashboard-sidebar-inner" data-simplebar>
    <div class="dashboard-nav-container">

      <!-- Responsive Navigation Trigger -->
      <a href="#" class="dashboard-responsive-nav-trigger">
        <span class="hamburger hamburger--collapse" >
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
          </span>
        </span>
        <span class="trigger-title">Navigation Menu</span>
      </a>

      <!-- Navigation -->
      <div class="dashboard-nav">
        <div class="dashboard-nav-inner">

          <ul data-submenu-title="Start">
            <li><a href="{{ url_for('manage.dashboard') }}"><i class="icon-material-outline-dashboard"></i> Dashboard</a></li>
            <li><a href="{{ url_for('message.messages') }}"><i class="icon-material-outline-question-answer"></i> Messages</a></li>
            <li><a href="#"><i class="icon-material-outline-star-border"></i> Bookmarks</a>
              <ul>
                <li><a href="{{ url_for('manage.bookmarkedTasks') }}">Bookmarked Projects</a></li>
                <li><a href="{{ url_for('manage.bookmarkedUsers') }}">Bookmarked Users</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for('manage.reviews') }}"><i class="icon-material-outline-rate-review"></i> Reviews</a></li>
          </ul>

          <ul data-submenu-title="Manage">
            <li><a href="#"><i class="icon-material-outline-assignment"></i>Manage Projects</a>
              <ul>
                {% if current_user.is_there_offer() %}
                  <li><a href="{{ url_for('manage.manageOffers') }}">Recieved Offers</a></li>
                {% endif %}
                <li><a href="{{ url_for('manage.manageTasks') }}">Posted Projects</a></li>
                {% if current_user.status == 'freelancer' %}
                  <li><a href="{{ url_for('manage.activeBids') }}">Active Bids</a></li>
                {% endif %}
                <li><a href="{{ url_for('posttask.post_task') }}">Post a Project</a></li>
              </ul>
            </li>
          </ul>

          <ul data-submenu-title="Account">
            <li><a href="{{ url_for('editProfile.editProfile_page') }}"><i class="icon-material-outline-account-circle"></i> Edit Profile</a></li>
            <li><a href="{{ url_for('setting.setting_page') }}"><i class="icon-material-outline-settings"></i> Settings</a></li>
            <li><a href="{{ url_for('account.logout') }}"><i class="icon-material-outline-power-settings-new"></i> Logout</a></li>
          </ul>

        </div>
      </div>
      <!-- Navigation / End -->

    </div>
  </div>
</div>